version: "3.9"

x-backend: &backend
  build:
    context: .
    dockerfile: backend.Dockerfile
    network: host
  environment:
    DEV_DOCKER: "true"
    DATABASE_URL: postgres://postgres:password@localhost:5432/cargo_registry
    SESSION_KEY: badkeyabcdefghijklmnopqrstuvwxyzabcdef
    GIT_REPO_URL: file:///app/tmp/index-bare
    GH_CLIENT_ID: ""
    GH_CLIENT_SECRET: ""
    WEB_ALLOWED_ORIGINS: http://localhost:8888,http://localhost:4200
  network_mode: "host"
  volumes:
    # Mount the src/ directory so we don't have to rebuild the Docker image
    # when we want to change some code
    - ./src:/app/src:ro

    - index:/app/tmp
    - cargo-cache:/usr/local/cargo/registry
    - target-cache:/app/target
    - local-uploads:/app/local_uploads

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 8

  backend:
    <<: *backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8888:8888

  worker:
    <<: *backend
    entrypoint: cargo run --bin background-worker
    depends_on:
      - backend

volumes:
  postgres-data:
  cargo-cache:
  target-cache:
  index:
  local-uploads:
