name: CI

on:
  push:
    branches:
      - auto
      - master
      - try

  pull_request:

env:
  DIESEL_CLI_VERSION: 2.0.1
  PNPM_VERSION: 7.14.2
  RUST_VERSION: 1.65.0

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-20.04
    env:
      JOBS: 1 # See https://git.io/vdao3 for details.

      # Percy secrets are included here to enable Percy's GitHub integration
      # on community-submitted PRs
      PERCY_TOKEN: 0d8707a02b19aebbec79bb0bf302b8d2fa95edb33169cfe41b084289596670b1
      PERCY_PROJECT: crates-io/crates.io

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v3.5.1
        with:
          cache: pnpm
          node-version-file: package.json

      - name: Install node modules
        run: pnpm install

      - name: Lint
        run: |
          pnpm lint:hbs
          pnpm lint:js
          pnpm lint:deps

      - name: Run percy exec
        if: github.repository == 'rust-lang/crates.io'
        run: pnpm percy exec -- pnpm test-coverage

      - name: test-coverage
        if: github.repository != 'rust-lang/crates.io'
        run: pnpm test-coverage

  backend-lint:
    name: Backend (linting)
    runs-on: ubuntu-20.04

    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - uses: actions/checkout@v3.1.0

      - run: rustup default ${{ env.RUST_VERSION }}
      - run: rustup component add rustfmt
      - run: rustup component add clippy

      - uses: Swatinem/rust-cache@v2.0.2

      - run: cargo fmt --check
      - run: cargo clippy --all-targets --all-features --all

  backend:
    name: Backend
    runs-on: ubuntu-20.04

    continue-on-error: ${{ matrix.rust != 'stable' }}
    strategy:
      matrix:
        rust:
          - stable
          - beta

    env:
      RUST_BACKTRACE: 1
      DATABASE_URL: postgres://postgres:postgres@localhost/cargo_registry_test
      TEST_DATABASE_URL: postgres://postgres:postgres@localhost/cargo_registry_test
      RUSTFLAGS: "-D warnings"
      MALLOC_CONF: "background_thread:true,abort_conf:true,abort:true,junk:true"

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Install ${{ env.RUST_VERSION }} Rust
        if: matrix.rust == 'stable'
        run: |
          rustup update ${{ env.RUST_VERSION }}
          rustup default ${{ env.RUST_VERSION }}

      - name: Install ${{ matrix.rust }} Rust
        if: matrix.rust != 'stable'
        run: |
          rustup update ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}

      - uses: Swatinem/rust-cache@v2.0.2

      - name: Setup database
        run: |
          cargo install diesel_cli --vers ${{ env.DIESEL_CLI_VERSION }} --no-default-features --features postgres --debug
          diesel database setup --locked-schema

      - name: Run tests
        run: cargo test --workspace
